name = "tabimap"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "trip-planner-db"
database_id = "c039f1ad-042a-4481-bf7a-55c54ebe6f92"

[vars]
NODE_VERSION = "22.14.0"
VITE_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsubmFrYXlhbWEtZGF5LXRyaXBzLnBhZ2VzLmRldiQ"
