import fs from "fs";
import path from "path";
import type { Destination } from "../src/shared/types/destination";

/**
 * Declarative source of truth for destination-to-hub relationships.
 *
 * - PARENT_BY_DESTINATION_ID: genuine municipal containment (destination is
 *   physically inside the parent hub's catchment, e.g. within ~60 km).
 * - GATEWAY_BY_DESTINATION_ID: regional access hubs for places that are only
 *   reachable via a gateway (islands, remote mountain areas) and are not
 *   contained within the hub's municipality.
 *
 * The script is idempotent. It validates every map entry up front (failures
 * abort with a non-zero exit), then reconciles the catalogue to the maps:
 * records whose current parent/gateway already matches are left untouched so
 * their serialization is byte-identical (minimal diff), while stale mappings
 * that were removed from the tables are propagated back to unparented.
 */
const PARENT_BY_DESTINATION_ID: Record<string, string> = {
  "abeno-harukas-300-osaka": "osaka-city",
  "akasaka-minato": "minato-city",
  "akihabara-chiyoda": "chiyoda-city",
  "akiu-onsen-miyagi": "sendai-city",
  "akiyoshido-cave-yamaguchi": "mine-city",
  "amanohashidate-kyoto": "miyazu-city",
  "ameya-yokocho": "taito-city",
  "aoba-castle-museum": "sendai-city",
  "arakurayama-sengen-park-yamanashi": "fujiyoshida-city",
  "arima-onsen": "kobe-city",
  "art-tower-mito": "mito-city",
  "asakusa-taito": "taito-city",
  "ashikaga-flower-park-tochigi": "ashikaga-city",
  "asuka-fujiwara-nara": "nara-city",
  "atsuta-shrine-nagoya": "nagoya-city",
  "beppu-hells-oita": "beppu-city",
  "bise-fukugi-tree-road-motobu": "motobu-town",
  "bitchu-matsuyama-castle": "takahashi-city",
  "boso-peninsula": "kisarazu-city",
  buaiso: "machida-tokyo",
  "busena-marine-park-nago": "nago-city",
  "byodoin-temple": "uji-city",
  "canal-city-hakata": "fukuoka-city",
  "chiba-city-folk-museum": "chiba-city",
  "chiba-city-museum-of-art": "chiba-city",
  "chiba-park": "chiba-city",
  "chiba-port-park": "chiba-city",
  "chiba-port-tower": "chiba-city",
  "chiba-sawara": "katori-city",
  "chiba-shrine": "chiba-city",
  "chiba-zoological-park": "chiba-city",
  "chofu-historic-jindaiji-district": "chofu-tokyo",
  "choshi-chiba": "choshi-city",
  "churaumi-aquarium-motobu": "motobu-town",
  "cup-noodles-museum-yokohama": "yokohama-city",
  "dakigaeri-valley-akita": "akita-city",
  "danjo-garan-koyasan": "koya-town",
  "dewa-sanzan-yamagata": "yamagata-city",
  disneyland: "urayasu-city",
  disneysea: "urayasu-city",
  "dogo-onsen-ehime": "matsuyama-city",
  dotonbori: "osaka-city",
  "edo-castle-tokyo": "chiyoda-city",
  engakuji: "kamakura-city",
  "engyo-ji-mount-shosha": "himeji-city",
  "enoshima-aquarium": "fujisawa-city",
  "enoshima-island": "fujisawa-city",
  "enoshima-iwaya-caves": "fujisawa-city",
  "enoshima-sea-candle": "fujisawa-city",
  "enoshima-shrine": "fujisawa-city",
  "enryaku-ji-mount-hiei": "otsu-city",
  "former-hokkaido-government-office": "sapporo-city",
  "fudaten-shrine": "chofu-tokyo",
  "fujiko-f-fujio-museum": "kawasaki-city",
  "fukagawa-edo-museum": "koto-city",
  "fukuoka-art-museum": "fukuoka-city",
  "fukuoka-castle-ruins": "fukuoka-city",
  "fukuoka-tower": "fukuoka-city",
  "fukuoka-yatai": "fukuoka-city",
  "fukushuen-garden-naha": "naha-city",
  "fushimi-inari-taisha": "kyoto-city",
  "genbudo-cave-park": "toyooka-city",
  "genkyuen-garden": "hikone-city",
  "gero-onsen": "gero-city",
  "gifu-castle-gifu": "gifu-city",
  "ginkaku-ji": "kyoto-city",
  "ginza-itoya": "chuo-city",
  "ginza-urban": "chuo-city",
  "golden-gai": "shinjuku-city",
  "goshikinuma-ponds-fukushima": "aizuwakamatsu-city",
  "gotoku-ji": "setagaya-city",
  "gunkanjima-hashima-nagasaki": "nagasaki-city",
  "gunma-ikaho-onsen": "kusatsu-town",
  "gunma-shima-onsen": "kusatsu-town",
  "gyokudo-art-museum": "ome-tokyo",
  "hachioji-castle-tokyo": "hachioji-tokyo",
  "hakata-machiya-folk-museum": "fukuoka-city",
  hakkeijima: "yokohama-city",
  "hakodate-night-view": "hakodate-city",
  "hamarikyu-gardens": "chuo-city",
  "harajuku-takeshita-street": "shibuya-city",
  "harry-potter-studio": "nerima-city",
  hasedera: "kamakura-city",
  "heian-jingu": "kyoto-city",
  "hiei-zan-driveway-observatory": "otsu-city",
  "higashi-hennazaki-cape-miyako": "miyakojima-city",
  "higashiyama-sky-tower-nagoya": "nagoya-city",
  "hijikata-toshizo-museum": "hino-city",
  "hikone-castle-shiga": "hikone-city",
  "himeji-castle": "himeji-city",
  "hirosaki-castle": "hirosaki-city",
  "hiroshima-castle": "hiroshima-city",
  "hiroshima-museum-art": "hiroshima-city",
  "hiroshima-peace-memorial": "hiroshima-city",
  "hokkaido-jingu": "sapporo-city",
  "hokkaido-museum-of-modern-art": "sapporo-city",
  "hokki-ji-pagoda": "ikaruga-town",
  hokokuji: "kamakura-city",
  "honmaru-palace": "nagoya-city",
  "horyuji-temple-nara": "ikaruga-town",
  "ikebukuro-toshima": "toshima-city",
  "ikuno-silver-mine": "asago-city",
  "ikuta-ryokuchi": "kawasaki-city",
  "imperial-palace-chiyoda": "chiyoda-city",
  "inage-seaside-park": "chiba-city",
  inamuragasaki: "kamakura-city",
  "inuyama-castle-aichi": "inuyama-city",
  "irabu-bridge-irabujima-miyako": "miyakojima-city",
  "ise-grand-shrine": "ise-city",
  "iwatsuki-ningyo-museum": "saitama-city",
  "izumo-taisha": "izumo-city",
  "izushi-castle-town": "toyooka-city",
  "jindai-botanical-gardens": "chofu-tokyo",
  jindaiji: "chofu-tokyo",
  "jochi-ji": "kamakura-city",
  joypolis: "koto-city",
  "jozenji-dori": "sendai-city",
  "kabira-bay-ishigaki": "ishigaki-city",
  kabukicho: "shinjuku-city",
  kabukiza: "chuo-city",
  kagurazaka: "shinjuku-city",
  "kairakuen-mito": "mito-city",
  "kakunodate-samurai-district-akita": "semboku-city",
  "kamakurakokomae-station": "kamakura-city",
  "kanayama-shrine": "kawasaki-city",
  "kannai-yokohama": "yokohama-city",
  "kasamatsu-park-view": "miyazu-city",
  "kashiya-yokocho": "kawagoe-city",
  "kasori-shell-mounds": "chiba-city",
  "kataonami-beach-wakanoura": "wakayama-city",
  "katase-higashihama-beach": "fujisawa-city",
  "kawagoe-castle-saitama": "kawagoe-city",
  "kawagoe-festival-museum": "kawagoe-city",
  "kawagoe-hikawa-shrine": "kawagoe-city",
  "kawasaki-daishi": "kawasaki-city",
  "kegon-falls-nikko": "nikko-city",
  "keio-mogusaen": "hino-city",
  "keio-rail-land": "hino-city",
  "kennin-ji": "kyoto-city",
  "kimii-dera-temple": "wakayama-city",
  "kinkaku-ji": "kyoto-city",
  "kinosaki-onsen": "toyooka-city",
  "kintai-bridge-yamaguchi": "iwakuni-city",
  "kinugawa-onsen": "nikko-city",
  "kirin-beer-yokohama-factory": "yokohama-city",
  "kita-in": "kawagoe-city",
  "kitano-ijinkan": "kobe-city",
  "kitaro-chaya": "chofu-tokyo",
  "kiyosumi-gardens": "koto-city",
  "kobe-animal-kingdom": "kobe-city",
  "kobe-harborland": "kobe-city",
  "kobe-maritime-museum": "kobe-city",
  "kobe-maya-night-view": "kobe-city",
  "kobe-port-tower": "kobe-city",
  "kochi-castle": "kochi-city",
  "koko-en-garden": "himeji-city",
  "kokusai-dori-naha": "naha-city",
  "komachi-street": "kamakura-city",
  "korakuen-okayama": "okayama-city",
  "kotoku-in-great-buddha": "kamakura-city",
  "kouri-island-okinawa": "nago-city",
  "kumamoto-castle": "kumamoto-city",
  "kumano-kodo-koya-wakayama": "koya-town",
  "kurazukuri-warehouse-district": "kawagoe-city",
  "kuromon-market": "osaka-city",
  "kuroshio-market-marina-city": "wakayama-city",
  "kushida-shrine": "fukuoka-city",
  "kyoto-historic": "kyoto-city",
  "kyoto-imperial-palace": "kyoto-city",
  "kyoto-international-manga-museum": "kyoto-city",
  "kyoto-national-museum": "kyoto-city",
  "kyoto-railway-museum": "kyoto-city",
  "lake-biwa-shiga": "otsu-city",
  "lake-towada-aomori": "aomori-city",
  "lazona-kawasaki-plaza": "kawasaki-city",
  "machida-graphic-arts-museum": "machida-tokyo",
  "maizuru-park": "fukuoka-city",
  "makuhari-seaside-park": "chiba-city",
  "marugame-castle": "marugame-city",
  "maruyama-park": "sapporo-city",
  "matsue-castle": "matsue-city",
  "matsumoto-castle-nagano": "matsumoto-city",
  "matsushima-bay": "sendai-city",
  "matsuyama-castle-ehime": "matsuyama-city",
  "meiji-jingu": "shibuya-city",
  "meoto-iwa-wedded-rocks": "ise-city",
  "meriken-park": "kobe-city",
  "mimuroto-ji-temple": "uji-city",
  "minato-mirai-yokohama": "yokohama-city",
  "mirai-tower-nagoya": "nagoya-city",
  miraikan: "koto-city",
  "mitaki-dera": "hiroshima-city",
  "mito-castle-ibaraki": "mito-city",
  "miyajima-itsukushima": "hatsukaichi-city",
  "mount-aso-kumamoto": "aso-city",
  "mount-bandai-fukushima": "aizuwakamatsu-city",
  "mount-inasa-nagasaki": "nagasaki-city",
  "mount-moiwa": "sapporo-city",
  "mount-takao": "hachioji-tokyo",
  "mount-yoshino-nara": "nara-city",
  "mount-zao-yamagata": "yamagata-city",
  "mozufuruichi-kofun-osaka": "sakai-city",
  "mukojima-hyakkaen": "sumida-city",
  "musashi-ichinomiya-hikawa-shrine": "saitama-city",
  "musashi-mitake-shrine": "ome-tokyo",
  "museum-contemporary-art-tokyo": "koto-city",
  "museum-of-aeronautical-sciences": "narita-city",
  "nagano-kamikochi": "matsumoto-city",
  "nago-pineapple-park": "nago-city",
  "nagoya-castle-aichi": "nagoya-city",
  "nagoya-city-art-museum": "nagoya-city",
  "nagoya-city-science-museum": "nagoya-city",
  "nagoya-port-tower": "nagoya-city",
  "nakanoshima-museum-art-osaka": "osaka-city",
  nakasu: "fukuoka-city",
  "nakijin-castle-ruins-motobu": "motobu-town",
  "naminoue-shrine-naha": "naha-city",
  "nankinmachi-chinatown": "kobe-city",
  "nanzen-ji": "kyoto-city",
  "nara-historic": "nara-city",
  "nara-park-todaiji": "nara-city",
  "naramachi-historic-district": "nara-city",
  "narita-airport-observation-decks": "narita-city",
  "naritasan-park": "narita-city",
  "national-museum-of-nature-and-science": "taito-city",
  "national-museum-western-art-tokyo": "taito-city",
  "nebuta-museum-wa-rasse-aomori": "aomori-city",
  "nihon-minka-en": "kawasaki-city",
  nihonbashi: "chuo-city",
  "nijo-castle-kyoto": "kyoto-city",
  "nijo-market": "sapporo-city",
  "nikko-toshogu-shrine-tochigi": "nikko-city",
  "ninna-ji": "kyoto-city",
  "nishiki-market": "kyoto-city",
  "nozuta-park": "machida-tokyo",
  "nunobiki-falls": "kobe-city",
  "nunobiki-herb-gardens": "kobe-city",
  "nunobiki-ropeway": "kobe-city",
  "nyuto-onsen-akita": "semboku-city",
  "odaiba-minato": "koto-city",
  "odori-park": "sapporo-city",
  "ohori-park": "fukuoka-city",
  "okage-yokocho-oharai-machi": "ise-city",
  "okama-crater-yamagata": "yamagata-city",
  "okinoshima-munakata-fukuoka": "fukuoka-city",
  okonomimura: "hiroshima-city",
  "okunoin-cemetery-koyasan": "koya-town",
  "ome-railway-park": "ome-tokyo",
  "ome-retro-town": "ome-tokyo",
  "omiya-bonsai-art-museum": "saitama-city",
  "omiya-bonsai-village": "saitama-city",
  "omiya-park": "saitama-city",
  "omiya-railway": "saitama-city",
  "omoide-yokocho": "shinjuku-city",
  "orizuru-tower": "hiroshima-city",
  "osaka-aquarium-kaiyukan": "osaka-city",
  "osaka-castle": "osaka-city",
  "osaka-castle-park": "osaka-city",
  "osaka-central-public-hall": "osaka-city",
  "osaka-museum-of-housing-and-living": "osaka-city",
  "osaka-station-city": "osaka-city",
  "osaki-hachimangu": "sendai-city",
  "osu-kannon": "nagoya-city",
  "osu-shopping-district": "nagoya-city",
  "oura-church-nagasaki": "nagasaki-city",
  "philosopher-s-walk": "kyoto-city",
  "play-museum-tachikawa": "tachikawa-tokyo",
  "polar-science-museum": "tachikawa-tokyo",
  "rakuten-mobile-park-miyagi": "sendai-city",
  renkeiji: "kawagoe-city",
  "ritsuunkyo-viewpoint": "asago-city",
  "roppongi-hills-tokyo-city-view": "minato-city",
  "ryoan-ji": "kyoto-city",
  "ryogoku-kokugikan-sumo-museum": "sumida-city",
  "ryugado-cave-kochi": "kochi-city",
  "ryusendo-cave-iwate": "morioka-city",
  "saitama-shintoshin": "saitama-city",
  "saitama-stadium-2002": "saitama-city",
  "saitama-super-arena": "saitama-city",
  "sakai-city-museum": "sakai-city",
  "sakurajima-volcano-kagoshima": "kagoshima-city",
  "samuel-cocking-garden": "fujisawa-city",
  "sanjusangen-do": "kyoto-city",
  "sannai-maruyama-jomon-aomori": "aomori-city",
  "sapporo-beer-museum": "sapporo-city",
  "sapporo-clock-tower": "sapporo-city",
  "sapporo-tv-tower": "sapporo-city",
  "sasuke-inari-shrine": "kamakura-city",
  "scmaglev-and-railway-park": "nagoya-city",
  "seiko-museum-ginza": "chuo-city",
  "sendai-asaichi-morning-market": "sendai-city",
  "sendai-castle-ruins-miyagi": "sendai-city",
  "sendai-city-museum": "sendai-city",
  "sendai-mediatheque": "sendai-city",
  "sendai-umino-mori-aquarium": "sendai-city",
  "senjojiki-sandanbeki-cliffs": "shirahama-town",
  "serigaya-park": "machida-tokyo",
  "shibuya-crossing-hachiko": "shibuya-city",
  "shibuya-sky-shibuya": "shibuya-city",
  "shin-yokohama-ramen-museum": "yokohama-city",
  "shingashi-river": "kawagoe-city",
  "shinjuku-gyo-en": "shinjuku-city",
  shinsaibashi: "osaka-city",
  shinsekai: "osaka-city",
  "shinsho-ji": "narita-city",
  "shirahama-beach-adventure-world": "shirahama-town",
  "shirakami-sanchi-aomori": "hirosaki-city",
  shitennoji: "osaka-city",
  "shonan-kaigan-park": "fujisawa-city",
  "showa-kinen-park": "tachikawa-tokyo",
  shukkeien: "hiroshima-city",
  "shuri-castle-okinawa": "naha-city",
  "soji-ji-yokohama": "yokohama-city",
  "sugamo-jizo-dori": "toshima-city",
  "sumida-hokusai-museum": "sumida-city",
  "sumida-river-walk": "sumida-city",
  "sunshine-60-observatory-ikebukuro": "toshima-city",
  "sunshine-aquarium": "toshima-city",
  "sunshine-city": "toshima-city",
  susukino: "sapporo-city",
  "suwa-shrine-tachikawa": "tachikawa-tokyo",
  "tachikawa-manga-park": "tachikawa-tokyo",
  "taisho-roman-street": "kawagoe-city",
  "takahata-fudoson": "hachioji-tokyo",
  "takanawa-gateway-minato": "minato-city",
  "takao-599-museum": "hachioji-tokyo",
  "takaosan-yakuoin": "hachioji-tokyo",
  "takeda-castle-ruins-hyogo": "asago-city",
  "takeda-castle-yamanashi": "kofu-city",
  "tama-forest-science-garden": "hachioji-tokyo",
  "tama-zoological-park": "hino-city",
  "tamatorizaki-viewpoint-ishigaki": "ishigaki-city",
  "tanukikoji-shopping-street": "sapporo-city",
  "taro-okamoto-museum-of-art": "kawasaki-city",
  "teamlab-borderless-azabudai": "minato-city",
  "teamlab-planets": "koto-city",
  "tempozan-ferris-wheel": "osaka-city",
  tenjin: "fukuoka-city",
  "tennoji-park": "osaka-city",
  "teshima-island-kagawa": "takamatsu-city",
  "the-museum-of-modern-art-saitama": "saitama-city",
  "the-national-museum-of-art-osaka": "osaka-city",
  tochoji: "fukuoka-city",
  "todoroki-ryokuchi": "kawasaki-city",
  "toki-messe-tower-niigata": "niigata-city",
  "toki-no-kane": "kawagoe-city",
  "tokiwaso-manga-museum": "toshima-city",
  "tokugawa-art-museum": "nagoya-city",
  "tokugawa-garden": "nagoya-city",
  "tokyo-hinohara": "hachioji-tokyo",
  "tokyo-metropolitan-government-building-shinjuku": "shinjuku-city",
  "tokyo-mt-mitake": "ome-tokyo",
  "tokyo-national-museum": "taito-city",
  "tokyo-okutama": "ome-tokyo",
  "tokyo-skytree-sumida": "sumida-city",
  "tokyo-station-chiyoda": "chiyoda-city",
  "tokyo-tower-minato": "minato-city",
  "tomogashima-islands": "wakayama-city",
  "toshiba-science-museum": "kawasaki-city",
  "toshodai-ji-temple": "nara-city",
  "tottori-sand-dunes": "tottori-city",
  "toyosu-market": "koto-city",
  "toyota-commemorative-museum-of-industry-and-technology": "nagoya-city",
  "tsujido-seaside-park": "fujisawa-city",
  "tsukiji-outer-market": "chuo-city",
  "tsunoshima-bridge-yamaguchi": "shimonoseki-city",
  "tsuruga-castle-fukushima": "aizuwakamatsu-city",
  "tsurugaoka-hachimangu": "kamakura-city",
  tsutenkaku: "osaka-city",
  "ueda-castle-nagano": "nagano-city",
  "ueno-park": "taito-city",
  "ueno-taito": "taito-city",
  "ueno-zoo": "ueno-taito",
  "uji-tea-culture-center": "uji-city",
  "ukimido-mangetsu-ji": "otsu-city",
  "umeda-sky-building": "osaka-city",
  "universal-studios-japan": "osaka-city",
  "utsunomiya-oya": "utsunomiya-city",
  "wakayama-castle": "wakayama-city",
  "yakushi-ike-park": "machida-tokyo",
  "yakushi-ji-temple": "nara-city",
  "yamadera-yamagata": "yamagata-city",
  "yamanashi-fujiyoshida": "fujiyoshida-city",
  "yamanashi-nishizawa-valley": "kofu-city",
  "yamanashi-shosenkyo-gorge": "kofu-city",
  "yamashita-park-yokohama": "yokohama-city",
  yanaka: "taito-city",
  "yasaka-shrine": "kyoto-city",
  "yokohama-chinatown": "yokohama-city",
  "yokohama-cosmo-world": "yokohama-city",
  "yokohama-landmark-tower-sky-garden": "yokohama-city",
  "yokohama-marine-tower": "yokohama-city",
  "yokohama-red-brick-warehouse": "yokohama-city",
  "yokohama-zoorasia": "yokohama-city",
  "yonaha-maehama-beach-miyako": "miyakojima-city",
  "yonehara-beach-coral-ishigaki": "ishigaki-city",
  "yoyogi-park": "shibuya-city",
  "yugyo-ji": "fujisawa-city",
  "yuigahama-beach": "kamakura-city",
  "zeniarai-benten": "kamakura-city",
  "zoshigaya-kishimojindo": "toshima-city",
  zuihoden: "sendai-city",
  "fuji-5-lake": "fujikawaguchiko-town",
  "gunma-kusatsu-onsen": "kusatsu-town",
  "ibaraki-mount-tsukuba": "tsukuba-city",
  izu: "ito-city",
  kiso: "matsumoto-city",
  "lake-hamanako": "hamamatsu-city",
  "lake-sagami": "sagamihara-city",
  okuhida: "takayama-city",
  "oze-national-park": "minakami-town",
  "saitama-nagatoro": "chichibu-city",
};

const GATEWAY_BY_DESTINATION_ID: Record<string, string> = {
  "shirahige-shrine-lake-biwa": "Shiga:takashima",
  "omi-hachiman-canal": "Shiga:omihachiman",
  "kishi-station-tama-cat": "Wakayama:kinokawa",
  "ine-funaya-boathouses": "Kyoto:ine",
  // PR #88 gateway conversions, reviewed in PR #89 audit (docs/audits/pr89-gateway-review.csv).
  // Each entry represents a practical regional access hub for a destination that is
  // geographically distant or cross-municipality from the hub.
  "chogosonshi-ji-temple": "ikaruga-town",

  "zao-fox-village-miyagi": "sendai-city",

  "chiba-yoro-valley": "chiba-city",

  zushi: "yokosuka-city",

  jogashima: "yokosuka-city",

  "iwami-ginzan-shimane": "izumo-city",

  "ibaraki-hitachi-seaside-park": "mito-city",

  "ibaraki-fukuroda-falls": "mito-city",

  "gifu-magome-juku": "gifu-city",

  "gifu-gujo-hachiman": "gifu-city",

  "nagano-bessho-onsen": "nagano-city",

  "ouchi-juku-fukushima": "aizuwakamatsu-city",

  "sado-island": "niigata-city",

  "chiba-nokogiriyama": "kisarazu-city",

  "motonosumi-shrine-yamaguchi": "shimonoseki-city",

  "kakegawa-castle-shizuoka": "hamamatsu-city",

  "mother-farm-chiba": "kisarazu-city",

  "oarai-marine-tower": "mito-city",

  "sakura-castle-chiba": "narita-city",

  "abukuma-cave-fukushima": "aizuwakamatsu-city",
  "amami-iriomote-natural-site": "kagoshima-city",
  "geibikei-gorge-iwate": "morioka-city",
  "ginzan-onsen-yamagata": "yamagata-city",
  "hiraizumi-chusonji-iwate": "morioka-city",
  "iya-valley-tokushima": "tokushima-city",
  "jodogahama-beach-iwate": "morioka-city",
  "nagano-tsumago-juku": "matsumoto-city",
  "naoshima-art-island-kagawa": "takamatsu-city",
  "shiretoko-national-park-hokkaido": "abashiri-city",
  "uwajima-castle": "matsuyama-city",
  "yakushima-town": "kagoshima-city",
  "cupnoodles-museum-osaka-ikeda": "sakai-city",
  "lake-tazawa-akita": "akita-city",
  "miho-museum-koka": "hikone-city",
  "nachi-falls-wakayama": "shirahama-town",
  "nagano-narai-juku": "matsumoto-city",
  "nagano-suwa": "matsumoto-city",
  "oirase-gorge-aomori": "aomori-city",
  "takato-castle-nagano": "matsumoto-city",
};

export const UNPARENTED_DESTINATION_IDS = [
  "ashigara",
  "boso-no-mura",
  "fukui",
  "gala-yuzawa",
  "ghibli-museum",
  "kanazawa",
  "kanazawa-castle-ishikawa",
  "katori-jingu",
  "kiyotsu-gorge-niigata",
  "kurobe-gorge",
  "maruoka-castle-fukui",
  "mount-fuji",
  "noto",
  "ogasawara-islands-tokyo",
  "takaoka",
  "tojinbo-cliffs-fukui",
  "tomioka-silk-mill-gunma",
  "toyama-alpine",
  "ushiku-daibutsu",
  "yomiuriland",
] as const;

const REGION_OVERRIDES: Record<string, string> = {
  "shuri-castle-okinawa": "Okinawa",
};

/**
 * Independent source of truth for destination municipalities, in
 * "prefecture:municipality" form (e.g. "Tokyo:chuo"). This map is authored
 * independently of PARENT_BY_DESTINATION_ID: the reconcile loop below never
 * derives or overwrites municipalityId from a parent relationship, so a wrong
 * containment link cannot silently rewrite a destination's municipality to
 * match. Entries here are the authoritative claim; the relationships validator
 * cross-checks contained destinations against their parent hub's municipality.
 */
const MUNICIPALITY_BY_DESTINATION_ID: Record<string, string> = {
  zushi: "Kanagawa:zushi",

  jogashima: "Kanagawa:miura",

  yomiuriland: "Tokyo:inagi",

  "abashiri-city": "Hokkaido:abashiri",
  "abeno-harukas-300-osaka": "Osaka:osaka",
  "adachi-city": "Tokyo:adachi",
  "aizuwakamatsu-city": "Fukushima:aizuwakamatsu",
  "akasaka-minato": "Tokyo:minato",
  "akihabara-chiyoda": "Tokyo:chiyoda",
  "akita-city": "Akita:akita",
  "akiu-onsen-miyagi": "Miyagi:sendai",
  "akiyoshido-cave-yamaguchi": "Yamaguchi:mine",
  "amanohashidate-kyoto": "Kyoto:miyazu",
  "ameya-yokocho": "Tokyo:taito",
  "aoba-castle-museum": "Miyagi:sendai",
  "aomori-city": "Aomori:aomori",
  "arakawa-city": "Tokyo:arakawa",
  "arakurayama-sengen-park-yamanashi": "Yamanashi:fujiyoshida",
  "arima-onsen": "Hyogo:kobe",
  "art-tower-mito": "Ibaraki:mito",
  "asago-city": "Hyogo:asago",
  "asahikawa-city": "Hokkaido:asahikawa",
  "asakusa-taito": "Tokyo:taito",
  "ashikaga-city": "Tochigi:ashikaga",
  "ashikaga-flower-park-tochigi": "Tochigi:ashikaga",
  "aso-city": "Kumamoto:aso",
  "asuka-fujiwara-nara": "Nara:nara",
  "atami-city": "Shizuoka:atami",
  "atsuta-shrine-nagoya": "Aichi:nagoya",
  "beppu-city": "Oita:beppu",
  "beppu-hells-oita": "Oita:beppu",
  "biei-town": "Hokkaido:biei",
  "bise-fukugi-tree-road-motobu": "Okinawa:motobu",
  "bitchu-matsuyama-castle": "Okayama:takahashi",
  "boso-peninsula": "Chiba:kisarazu",
  buaiso: "Tokyo:machida",
  "bunkyo-city": "Tokyo:bunkyo",
  "busena-marine-park-nago": "Okinawa:nago",
  "byodoin-temple": "Kyoto:uji",
  "canal-city-hakata": "Fukuoka:fukuoka",
  "chiba-city": "Chiba:chiba",
  "chiba-city-folk-museum": "Chiba:chiba",
  "chiba-city-museum-of-art": "Chiba:chiba",
  "chiba-nokogiriyama": "Chiba:kyonan",
  "chiba-park": "Chiba:chiba",
  "chiba-port-park": "Chiba:chiba",
  "chiba-port-tower": "Chiba:chiba",
  "chiba-sawara": "Chiba:katori",
  "chiba-shrine": "Chiba:chiba",
  "chiba-yoro-valley": "Chiba:otaki",
  "chiba-zoological-park": "Chiba:chiba",
  "chichibu-city": "Saitama:chichibu",
  "chigasaki-city": "Kanagawa:chigasaki",
  "chiyoda-city": "Tokyo:chiyoda",
  "chofu-historic-jindaiji-district": "Tokyo:chofu",
  "chofu-tokyo": "Tokyo:chofu",
  "chogosonshi-ji-temple": "Nara:heguri",
  "choshi-chiba": "Chiba:choshi",
  "choshi-city": "Chiba:choshi",
  "chuo-city": "Tokyo:chuo",
  "churaumi-aquarium-motobu": "Okinawa:motobu",
  "cup-noodles-museum-yokohama": "Kanagawa:yokohama",
  "dakigaeri-valley-akita": "Akita:akita",
  "danjo-garan-koyasan": "Wakayama:koya",
  "dazaifu-city": "Fukuoka:dazaifu",
  "dewa-sanzan-yamagata": "Yamagata:yamagata",
  disneyland: "Chiba:urayasu",
  disneysea: "Chiba:urayasu",
  "dogo-onsen-ehime": "Ehime:matsuyama",
  dotonbori: "Osaka:osaka",
  "edo-castle-tokyo": "Tokyo:chiyoda",
  "edogawa-city": "Tokyo:edogawa",
  engakuji: "Kanagawa:kamakura",
  "engyo-ji-mount-shosha": "Hyogo:himeji",
  "enoshima-aquarium": "Kanagawa:fujisawa",
  "enoshima-island": "Kanagawa:fujisawa",
  "enoshima-iwaya-caves": "Kanagawa:fujisawa",
  "enoshima-sea-candle": "Kanagawa:fujisawa",
  "enoshima-shrine": "Kanagawa:fujisawa",
  "enryaku-ji-mount-hiei": "Shiga:otsu",
  "former-hokkaido-government-office": "Hokkaido:sapporo",
  "fudaten-shrine": "Tokyo:chofu",
  "fuji-5-lake": "Yamanashi:fujikawaguchiko",
  "fujikawaguchiko-town": "Yamanashi:fujikawaguchiko",
  "fujiko-f-fujio-museum": "Kanagawa:kawasaki",
  "fujinomiya-city": "Shizuoka:fujinomiya",
  "fujisawa-city": "Kanagawa:fujisawa",
  "fujiyoshida-city": "Yamanashi:fujiyoshida",
  "fukagawa-edo-museum": "Tokyo:koto",
  "fukuoka-art-museum": "Fukuoka:fukuoka",
  "fukuoka-castle-ruins": "Fukuoka:fukuoka",
  "fukuoka-city": "Fukuoka:fukuoka",
  "fukuoka-tower": "Fukuoka:fukuoka",
  "fukuoka-yatai": "Fukuoka:fukuoka",
  "fukushima-city": "Fukushima:fukushima",
  "fukushuen-garden-naha": "Okinawa:naha",
  "funabashi-city": "Chiba:funabashi",
  "furano-city": "Hokkaido:furano",
  "fushimi-inari-taisha": "Kyoto:kyoto",
  "genbudo-cave-park": "Hyogo:toyooka",
  "genkyuen-garden": "Shiga:hikone",
  "gero-city": "Gifu:gero",
  "gero-onsen": "Gifu:gero",
  "ghibli-museum": "Tokyo:mitaka",
  "gifu-castle-gifu": "Gifu:gifu",
  "gifu-city": "Gifu:gifu",
  "gifu-gujo-hachiman": "Gifu:gujo",
  "gifu-magome-juku": "Gifu:nakatsugawa",
  "ginkaku-ji": "Kyoto:kyoto",
  "ginza-itoya": "Tokyo:chuo",
  "ginza-urban": "Tokyo:chuo",
  "golden-gai": "Tokyo:shinjuku",
  "goshikinuma-ponds-fukushima": "Fukushima:aizuwakamatsu",
  "gotemba-city": "Shizuoka:gotemba",
  "gotoku-ji": "Tokyo:setagaya",
  "gunkanjima-hashima-nagasaki": "Nagasaki:nagasaki",
  "gunma-ikaho-onsen": "Gunma:kusatsu",
  "gunma-kusatsu-onsen": "Gunma:kusatsu",
  "gunma-shima-onsen": "Gunma:kusatsu",
  "gyokudo-art-museum": "Tokyo:ome",
  "hachinohe-city": "Aomori:hachinohe",
  "hachioji-castle-tokyo": "Tokyo:hachioji",
  "hachioji-tokyo": "Tokyo:hachioji",
  "hakata-machiya-folk-museum": "Fukuoka:fukuoka",
  hakkeijima: "Kanagawa:yokohama",
  "hakodate-city": "Hokkaido:hakodate",
  "hakodate-night-view": "Hokkaido:hakodate",
  "hakone-town": "Kanagawa:hakone",
  "hakuba-village": "Nagano:hakuba",
  "hamamatsu-city": "Shizuoka:hamamatsu",
  "hamarikyu-gardens": "Tokyo:chuo",
  "harajuku-takeshita-street": "Tokyo:shibuya",
  "harry-potter-studio": "Tokyo:nerima",
  hasedera: "Kanagawa:kamakura",
  "hatsukaichi-city": "Hiroshima:hatsukaichi",
  "heian-jingu": "Kyoto:kyoto",
  "hiei-zan-driveway-observatory": "Shiga:otsu",
  "higashi-hennazaki-cape-miyako": "Okinawa:miyakojima",
  "higashiyama-sky-tower-nagoya": "Aichi:nagoya",
  "hijikata-toshizo-museum": "Tokyo:hino",
  "hikone-castle-shiga": "Shiga:hikone",
  "hikone-city": "Shiga:hikone",
  "himeji-castle": "Hyogo:himeji",
  "himeji-city": "Hyogo:himeji",
  "hino-city": "Tokyo:hino",
  "hirosaki-castle": "Aomori:hirosaki",
  "hirosaki-city": "Aomori:hirosaki",
  "hiroshima-castle": "Hiroshima:hiroshima",
  "hiroshima-city": "Hiroshima:hiroshima",
  "hiroshima-museum-art": "Hiroshima:hiroshima",
  "hiroshima-peace-memorial": "Hiroshima:hiroshima",
  "hokkaido-jingu": "Hokkaido:sapporo",
  "hokkaido-museum-of-modern-art": "Hokkaido:sapporo",
  "hokki-ji-pagoda": "Nara:ikaruga",
  hokokuji: "Kanagawa:kamakura",
  "honmaru-palace": "Aichi:nagoya",
  "horyuji-temple-nara": "Nara:ikaruga",
  "ibaraki-fukuroda-falls": "Ibaraki:daigo",
  "ibaraki-hitachi-seaside-park": "Ibaraki:hitachinaka",
  "ibaraki-mount-tsukuba": "Ibaraki:tsukuba",
  "ikaruga-town": "Nara:ikaruga",
  "ikebukuro-toshima": "Tokyo:toshima",
  "ikuno-silver-mine": "Hyogo:asago",
  "ikuta-ryokuchi": "Kanagawa:kawasaki",
  "imperial-palace-chiyoda": "Tokyo:chiyoda",
  "inage-seaside-park": "Chiba:chiba",
  inamuragasaki: "Kanagawa:kamakura",
  "ine-funaya-boathouses": "Kyoto:miyazu",
  "inuyama-castle-aichi": "Aichi:inuyama",
  "inuyama-city": "Aichi:inuyama",
  "irabu-bridge-irabujima-miyako": "Okinawa:miyakojima",
  "ise-city": "Mie:ise",
  "ise-grand-shrine": "Mie:ise",
  "ishigaki-city": "Okinawa:ishigaki",
  "itabashi-city": "Tokyo:itabashi",
  "ito-city": "Shizuoka:ito",
  "iwakuni-city": "Yamaguchi:iwakuni",
  "iwami-ginzan-shimane": "Shimane:oda",
  "iwatsuki-ningyo-museum": "Saitama:saitama",
  izu: "Shizuoka:ito",
  "izumo-city": "Shimane:izumo",
  "izumo-taisha": "Shimane:izumo",
  "izushi-castle-town": "Hyogo:toyooka",
  "jindai-botanical-gardens": "Tokyo:chofu",
  jindaiji: "Tokyo:chofu",
  "jochi-ji": "Kanagawa:kamakura",
  joypolis: "Tokyo:koto",
  "jozenji-dori": "Miyagi:sendai",
  "kabira-bay-ishigaki": "Okinawa:ishigaki",
  kabukicho: "Tokyo:shinjuku",
  kabukiza: "Tokyo:chuo",
  "kagoshima-city": "Kagoshima:kagoshima",
  kagurazaka: "Tokyo:shinjuku",
  "kairakuen-mito": "Ibaraki:mito",
  "kakegawa-castle-shizuoka": "Shizuoka:kakegawa",
  "kakunodate-samurai-district-akita": "Akita:semboku",
  "kamakura-city": "Kanagawa:kamakura",
  "kamakurakokomae-station": "Kanagawa:kamakura",
  "kanayama-shrine": "Kanagawa:kawasaki",
  "kannai-yokohama": "Kanagawa:yokohama",
  "karuizawa-town": "Nagano:karuizawa",
  "kasamatsu-park-view": "Kyoto:miyazu",
  "kashiya-yokocho": "Saitama:kawagoe",
  "kasori-shell-mounds": "Chiba:chiba",
  "kataonami-beach-wakanoura": "Wakayama:wakayama",
  "katase-higashihama-beach": "Kanagawa:fujisawa",
  "katori-city": "Chiba:katori",
  "katsushika-city": "Tokyo:katsushika",
  "kawagoe-castle-saitama": "Saitama:kawagoe",
  "kawagoe-city": "Saitama:kawagoe",
  "kawagoe-festival-museum": "Saitama:kawagoe",
  "kawagoe-hikawa-shrine": "Saitama:kawagoe",
  "kawaguchi-city": "Saitama:kawaguchi",
  "kawasaki-city": "Kanagawa:kawasaki",
  "kawasaki-daishi": "Kanagawa:kawasaki",
  "kegon-falls-nikko": "Tochigi:nikko",
  "keio-mogusaen": "Tokyo:hino",
  "keio-rail-land": "Tokyo:hino",
  "kennin-ji": "Kyoto:kyoto",
  "kimii-dera-temple": "Wakayama:wakayama",
  "kinkaku-ji": "Kyoto:kyoto",
  "kinosaki-onsen": "Hyogo:toyooka",
  "kintai-bridge-yamaguchi": "Yamaguchi:iwakuni",
  "kinugawa-onsen": "Tochigi:nikko",
  "kirin-beer-yokohama-factory": "Kanagawa:yokohama",
  "kisarazu-city": "Chiba:kisarazu",
  "kishi-station-tama-cat": "Wakayama:wakayama",
  kiso: "Nagano:matsumoto",
  "kita-city": "Tokyo:kita",
  "kita-in": "Saitama:kawagoe",
  "kitakyushu-city": "Fukuoka:kitakyushu",
  "kitano-ijinkan": "Hyogo:kobe",
  "kitaro-chaya": "Tokyo:chofu",
  "kiyosumi-gardens": "Tokyo:koto",
  "kobe-animal-kingdom": "Hyogo:kobe",
  "kobe-city": "Hyogo:kobe",
  "kobe-harborland": "Hyogo:kobe",
  "kobe-maritime-museum": "Hyogo:kobe",
  "kobe-maya-night-view": "Hyogo:kobe",
  "kobe-port-tower": "Hyogo:kobe",
  "kochi-castle": "Kochi:kochi",
  "kochi-city": "Kochi:kochi",
  "kofu-city": "Yamanashi:kofu",
  "koko-en-garden": "Hyogo:himeji",
  "kokusai-dori-naha": "Okinawa:naha",
  "komachi-street": "Kanagawa:kamakura",
  "korakuen-okayama": "Okayama:okayama",
  "koriyama-city": "Fukushima:koriyama",
  "koto-city": "Tokyo:koto",
  "kotoku-in-great-buddha": "Kanagawa:kamakura",
  "kouri-island-okinawa": "Okinawa:nago",
  "koya-town": "Wakayama:koya",
  "kumamoto-castle": "Kumamoto:kumamoto",
  "kumamoto-city": "Kumamoto:kumamoto",
  "kumano-kodo-koya-wakayama": "Wakayama:koya",
  "kurashiki-city": "Okayama:kurashiki",
  "kurazukuri-warehouse-district": "Saitama:kawagoe",
  "kuromon-market": "Osaka:osaka",
  "kuroshio-market-marina-city": "Wakayama:wakayama",
  "kusatsu-town": "Gunma:kusatsu",
  "kushida-shrine": "Fukuoka:fukuoka",
  "kushiro-city": "Hokkaido:kushiro",
  "kyoto-city": "Kyoto:kyoto",
  "kyoto-historic": "Kyoto:kyoto",
  "kyoto-imperial-palace": "Kyoto:kyoto",
  "kyoto-international-manga-museum": "Kyoto:kyoto",
  "kyoto-national-museum": "Kyoto:kyoto",
  "kyoto-railway-museum": "Kyoto:kyoto",
  "lake-biwa-shiga": "Shiga:otsu",
  "lake-hamanako": "Shizuoka:hamamatsu",
  "lake-sagami": "Kanagawa:sagamihara",
  "lake-towada-aomori": "Aomori:aomori",
  "lazona-kawasaki-plaza": "Kanagawa:kawasaki",
  "machida-graphic-arts-museum": "Tokyo:machida",
  "machida-tokyo": "Tokyo:machida",
  "maizuru-park": "Fukuoka:fukuoka",
  "makuhari-seaside-park": "Chiba:chiba",
  "marugame-castle": "Kagawa:marugame",
  "marugame-city": "Kagawa:marugame",
  "maruyama-park": "Hokkaido:sapporo",
  "matsudo-city": "Chiba:matsudo",
  "matsue-castle": "Shimane:matsue",
  "matsue-city": "Shimane:matsue",
  "matsumoto-castle-nagano": "Nagano:matsumoto",
  "matsumoto-city": "Nagano:matsumoto",
  "matsushima-bay": "Miyagi:sendai",
  "matsuyama-castle-ehime": "Ehime:matsuyama",
  "matsuyama-city": "Ehime:matsuyama",
  "meguro-city": "Tokyo:meguro",
  "meiji-jingu": "Tokyo:shibuya",
  "meoto-iwa-wedded-rocks": "Mie:ise",
  "meriken-park": "Hyogo:kobe",
  "mimuroto-ji-temple": "Kyoto:uji",
  "minakami-town": "Gunma:minakami",
  "minato-city": "Tokyo:minato",
  "minato-mirai-yokohama": "Kanagawa:yokohama",
  "mine-city": "Yamaguchi:mine",
  "mirai-tower-nagoya": "Aichi:nagoya",
  miraikan: "Tokyo:koto",
  "mitaki-dera": "Hiroshima:hiroshima",
  "mito-castle-ibaraki": "Ibaraki:mito",
  "mito-city": "Ibaraki:mito",
  "miyajima-itsukushima": "Hiroshima:hatsukaichi",
  "miyakojima-city": "Okinawa:miyakojima",
  "miyazaki-city": "Miyazaki:miyazaki",
  "miyazu-city": "Kyoto:miyazu",
  "morioka-city": "Iwate:morioka",
  "mother-farm-chiba": "Chiba:futtsu",
  "motobu-town": "Okinawa:motobu",
  "motonosumi-shrine-yamaguchi": "Yamaguchi:nagato",
  "mount-aso-kumamoto": "Kumamoto:aso",
  "mount-bandai-fukushima": "Fukushima:aizuwakamatsu",
  "mount-inasa-nagasaki": "Nagasaki:nagasaki",
  "mount-moiwa": "Hokkaido:sapporo",
  "mount-takao": "Tokyo:hachioji",
  "mount-yoshino-nara": "Nara:nara",
  "mount-zao-yamagata": "Yamagata:yamagata",
  "mozufuruichi-kofun-osaka": "Osaka:sakai",
  "mukojima-hyakkaen": "Tokyo:sumida",
  "musashi-ichinomiya-hikawa-shrine": "Saitama:saitama",
  "musashi-mitake-shrine": "Tokyo:ome",
  "museum-contemporary-art-tokyo": "Tokyo:koto",
  "museum-of-aeronautical-sciences": "Chiba:narita",
  "nagano-bessho-onsen": "Nagano:ueda",
  "nagano-city": "Nagano:nagano",
  "nagano-kamikochi": "Nagano:matsumoto",
  "nagasaki-city": "Nagasaki:nagasaki",
  "nago-city": "Okinawa:nago",
  "nago-pineapple-park": "Okinawa:nago",
  "nagoya-castle-aichi": "Aichi:nagoya",
  "nagoya-city": "Aichi:nagoya",
  "nagoya-city-art-museum": "Aichi:nagoya",
  "nagoya-city-science-museum": "Aichi:nagoya",
  "nagoya-port-tower": "Aichi:nagoya",
  "naha-city": "Okinawa:naha",
  "nakano-city": "Tokyo:nakano",
  "nakanoshima-museum-art-osaka": "Osaka:osaka",
  nakasu: "Fukuoka:fukuoka",
  "nakijin-castle-ruins-motobu": "Okinawa:motobu",
  "naminoue-shrine-naha": "Okinawa:naha",
  "nankinmachi-chinatown": "Hyogo:kobe",
  "nanzen-ji": "Kyoto:kyoto",
  "nara-city": "Nara:nara",
  "nara-historic": "Nara:nara",
  "nara-park-todaiji": "Nara:nara",
  "naramachi-historic-district": "Nara:nara",
  "narita-airport-observation-decks": "Chiba:narita",
  "narita-city": "Chiba:narita",
  "naritasan-park": "Chiba:narita",
  "naruto-city": "Tokushima:naruto",
  "national-museum-of-nature-and-science": "Tokyo:taito",
  "national-museum-western-art-tokyo": "Tokyo:taito",
  "nebuta-museum-wa-rasse-aomori": "Aomori:aomori",
  "nerima-city": "Tokyo:nerima",
  "nihon-minka-en": "Kanagawa:kawasaki",
  nihonbashi: "Tokyo:chuo",
  "niigata-city": "Niigata:niigata",
  "nijo-castle-kyoto": "Kyoto:kyoto",
  "nijo-market": "Hokkaido:sapporo",
  "nikko-city": "Tochigi:nikko",
  "nikko-toshogu-shrine-tochigi": "Tochigi:nikko",
  "ninna-ji": "Kyoto:kyoto",
  "niseko-town": "Hokkaido:niseko",
  "nishiki-market": "Kyoto:kyoto",
  "nozuta-park": "Tokyo:machida",
  "numazu-city": "Shizuoka:numazu",
  "nunobiki-falls": "Hyogo:kobe",
  "nunobiki-herb-gardens": "Hyogo:kobe",
  "nunobiki-ropeway": "Hyogo:kobe",
  "nyuto-onsen-akita": "Akita:semboku",
  "oarai-marine-tower": "Ibaraki:oarai",
  "odaiba-minato": "Tokyo:koto",
  "odawara-city": "Kanagawa:odawara",
  "odori-park": "Hokkaido:sapporo",
  "ohori-park": "Fukuoka:fukuoka",
  "okage-yokocho-oharai-machi": "Mie:ise",
  "okama-crater-yamagata": "Yamagata:yamagata",
  "okayama-city": "Okayama:okayama",
  "okazaki-city": "Aichi:okazaki",
  "okinoshima-munakata-fukuoka": "Fukuoka:fukuoka",
  okonomimura: "Hiroshima:hiroshima",
  okuhida: "Gifu:takayama",
  "okunoin-cemetery-koyasan": "Wakayama:koya",
  "ome-railway-park": "Tokyo:ome",
  "ome-retro-town": "Tokyo:ome",
  "ome-tokyo": "Tokyo:ome",
  "omi-hachiman-canal": "Shiga:otsu",
  "omiya-bonsai-art-museum": "Saitama:saitama",
  "omiya-bonsai-village": "Saitama:saitama",
  "omiya-park": "Saitama:saitama",
  "omiya-railway": "Saitama:saitama",
  "omoide-yokocho": "Tokyo:shinjuku",
  "onomichi-city": "Hiroshima:onomichi",
  "orizuru-tower": "Hiroshima:hiroshima",
  "osaka-aquarium-kaiyukan": "Osaka:osaka",
  "osaka-castle": "Osaka:osaka",
  "osaka-castle-park": "Osaka:osaka",
  "osaka-central-public-hall": "Osaka:osaka",
  "osaka-city": "Osaka:osaka",
  "osaka-museum-of-housing-and-living": "Osaka:osaka",
  "osaka-station-city": "Osaka:osaka",
  "osaki-hachimangu": "Miyagi:sendai",
  "osu-kannon": "Aichi:nagoya",
  "osu-shopping-district": "Aichi:nagoya",
  "ota-city": "Tokyo:ota",
  "otaru-city": "Hokkaido:otaru",
  "otsu-city": "Shiga:otsu",
  "ouchi-juku-fukushima": "Fukushima:shimogo",
  "oura-church-nagasaki": "Nagasaki:nagasaki",
  "oze-national-park": "Gunma:minakami",
  "philosopher-s-walk": "Kyoto:kyoto",
  "play-museum-tachikawa": "Tokyo:tachikawa",
  "polar-science-museum": "Tokyo:tachikawa",
  "rakuten-mobile-park-miyagi": "Miyagi:sendai",
  renkeiji: "Saitama:kawagoe",
  "ritsuunkyo-viewpoint": "Hyogo:asago",
  "roppongi-hills-tokyo-city-view": "Tokyo:minato",
  "ryoan-ji": "Kyoto:kyoto",
  "ryogoku-kokugikan-sumo-museum": "Tokyo:sumida",
  "ryugado-cave-kochi": "Kochi:kochi",
  "ryusendo-cave-iwate": "Iwate:morioka",
  "sado-island": "Niigata:sado",
  "sagamihara-city": "Kanagawa:sagamihara",
  "saitama-city": "Saitama:saitama",
  "saitama-nagatoro": "Saitama:chichibu",
  "saitama-shintoshin": "Saitama:saitama",
  "saitama-stadium-2002": "Saitama:saitama",
  "saitama-super-arena": "Saitama:saitama",
  "sakai-city": "Osaka:sakai",
  "sakai-city-museum": "Osaka:sakai",
  "sakura-castle-chiba": "Chiba:sakura",
  "sakurajima-volcano-kagoshima": "Kagoshima:kagoshima",
  "samuel-cocking-garden": "Kanagawa:fujisawa",
  "sanjusangen-do": "Kyoto:kyoto",
  "sannai-maruyama-jomon-aomori": "Aomori:aomori",
  "sapporo-beer-museum": "Hokkaido:sapporo",
  "sapporo-city": "Hokkaido:sapporo",
  "sapporo-clock-tower": "Hokkaido:sapporo",
  "sapporo-tv-tower": "Hokkaido:sapporo",
  "sasuke-inari-shrine": "Kanagawa:kamakura",
  "scmaglev-and-railway-park": "Aichi:nagoya",
  "seiko-museum-ginza": "Tokyo:chuo",
  "semboku-city": "Akita:semboku",
  "sendai-asaichi-morning-market": "Miyagi:sendai",
  "sendai-castle-ruins-miyagi": "Miyagi:sendai",
  "sendai-city": "Miyagi:sendai",
  "sendai-city-museum": "Miyagi:sendai",
  "sendai-mediatheque": "Miyagi:sendai",
  "sendai-umino-mori-aquarium": "Miyagi:sendai",
  "senjojiki-sandanbeki-cliffs": "Wakayama:shirahama",
  "serigaya-park": "Tokyo:machida",
  "setagaya-city": "Tokyo:setagaya",
  "shibuya-city": "Tokyo:shibuya",
  "shibuya-crossing-hachiko": "Tokyo:shibuya",
  "shibuya-sky-shibuya": "Tokyo:shibuya",
  "shimonoseki-city": "Yamaguchi:shimonoseki",
  "shin-yokohama-ramen-museum": "Kanagawa:yokohama",
  "shinagawa-city": "Tokyo:shinagawa",
  "shingashi-river": "Saitama:kawagoe",
  "shinjuku-city": "Tokyo:shinjuku",
  "shinjuku-gyo-en": "Tokyo:shinjuku",
  shinsaibashi: "Osaka:osaka",
  shinsekai: "Osaka:osaka",
  "shinsho-ji": "Chiba:narita",
  "shirahama-beach-adventure-world": "Wakayama:shirahama",
  "shirahama-town": "Wakayama:shirahama",
  "shirahige-shrine-lake-biwa": "Shiga:otsu",
  "shirakami-sanchi-aomori": "Aomori:hirosaki",
  "shirakawa-village": "Gifu:shirakawa",
  shitennoji: "Osaka:osaka",
  "shizuoka-city": "Shizuoka:shizuoka",
  "shonan-kaigan-park": "Kanagawa:fujisawa",
  "showa-kinen-park": "Tokyo:tachikawa",
  shukkeien: "Hiroshima:hiroshima",
  "shuri-castle-okinawa": "Okinawa:naha",
  "soji-ji-yokohama": "Kanagawa:yokohama",
  "sugamo-jizo-dori": "Tokyo:toshima",
  "suginami-city": "Tokyo:suginami",
  "sumida-city": "Tokyo:sumida",
  "sumida-hokusai-museum": "Tokyo:sumida",
  "sumida-river-walk": "Tokyo:sumida",
  "sunshine-60-observatory-ikebukuro": "Tokyo:toshima",
  "sunshine-aquarium": "Tokyo:toshima",
  "sunshine-city": "Tokyo:toshima",
  susukino: "Hokkaido:sapporo",
  "suwa-shrine-tachikawa": "Tokyo:tachikawa",
  "tachikawa-manga-park": "Tokyo:tachikawa",
  "tachikawa-tokyo": "Tokyo:tachikawa",
  "taisho-roman-street": "Saitama:kawagoe",
  "taito-city": "Tokyo:taito",
  "takachiho-town": "Miyazaki:takachiho",
  "takahashi-city": "Okayama:takahashi",
  "takahata-fudoson": "Tokyo:hachioji",
  "takamatsu-city": "Kagawa:takamatsu",
  "takanawa-gateway-minato": "Tokyo:minato",
  "takao-599-museum": "Tokyo:hachioji",
  "takaosan-yakuoin": "Tokyo:hachioji",
  "takayama-city": "Gifu:takayama",
  "takeda-castle-ruins-hyogo": "Hyogo:asago",
  "takeda-castle-yamanashi": "Yamanashi:kofu",
  "tama-forest-science-garden": "Tokyo:hachioji",
  "tama-zoological-park": "Tokyo:hino",
  "tamatorizaki-viewpoint-ishigaki": "Okinawa:ishigaki",
  "tanukikoji-shopping-street": "Hokkaido:sapporo",
  "taro-okamoto-museum-of-art": "Kanagawa:kawasaki",
  "teamlab-borderless-azabudai": "Tokyo:minato",
  "teamlab-planets": "Tokyo:koto",
  "tempozan-ferris-wheel": "Osaka:osaka",
  tenjin: "Fukuoka:fukuoka",
  "tennoji-park": "Osaka:osaka",
  "teshima-island-kagawa": "Kagawa:takamatsu",
  "the-museum-of-modern-art-saitama": "Saitama:saitama",
  "the-national-museum-of-art-osaka": "Osaka:osaka",
  tochoji: "Fukuoka:fukuoka",
  "todoroki-ryokuchi": "Kanagawa:kawasaki",
  "toki-messe-tower-niigata": "Niigata:niigata",
  "toki-no-kane": "Saitama:kawagoe",
  "tokiwaso-manga-museum": "Tokyo:toshima",
  "tokorozawa-city": "Saitama:tokorozawa",
  "tokugawa-art-museum": "Aichi:nagoya",
  "tokugawa-garden": "Aichi:nagoya",
  "tokushima-city": "Tokushima:tokushima",
  "tokyo-hinohara": "Tokyo:hachioji",
  "tokyo-metropolitan-government-building-shinjuku": "Tokyo:shinjuku",
  "tokyo-mt-mitake": "Tokyo:ome",
  "tokyo-national-museum": "Tokyo:taito",
  "tokyo-okutama": "Tokyo:ome",
  "tokyo-skytree-sumida": "Tokyo:sumida",
  "tokyo-station-chiyoda": "Tokyo:chiyoda",
  "tokyo-tower-minato": "Tokyo:minato",
  "tomogashima-islands": "Wakayama:wakayama",
  "toshiba-science-museum": "Kanagawa:kawasaki",
  "toshima-city": "Tokyo:toshima",
  "toshodai-ji-temple": "Nara:nara",
  "tottori-city": "Tottori:tottori",
  "tottori-sand-dunes": "Tottori:tottori",
  "toyooka-city": "Hyogo:toyooka",
  "toyosu-market": "Tokyo:koto",
  "toyota-city": "Aichi:toyota",
  "toyota-commemorative-museum-of-industry-and-technology": "Aichi:nagoya",
  "tsujido-seaside-park": "Kanagawa:fujisawa",
  "tsukiji-outer-market": "Tokyo:chuo",
  "tsukuba-city": "Ibaraki:tsukuba",
  "tsunoshima-bridge-yamaguchi": "Yamaguchi:shimonoseki",
  "tsuruga-castle-fukushima": "Fukushima:aizuwakamatsu",
  "tsurugaoka-hachimangu": "Kanagawa:kamakura",
  tsutenkaku: "Osaka:osaka",
  "ueda-castle-nagano": "Nagano:nagano",
  "ueno-park": "Tokyo:taito",
  "ueno-taito": "Tokyo:taito",
  "ueno-zoo": "Tokyo:taito",
  "uji-city": "Kyoto:uji",
  "uji-tea-culture-center": "Kyoto:uji",
  "ukimido-mangetsu-ji": "Shiga:otsu",
  "umeda-sky-building": "Osaka:osaka",
  "universal-studios-japan": "Osaka:osaka",
  "urayasu-city": "Chiba:urayasu",
  "ushiku-daibutsu": "Ibaraki:ushiku",
  "utsunomiya-city": "Tochigi:utsunomiya",
  "utsunomiya-oya": "Tochigi:utsunomiya",
  "wakayama-castle": "Wakayama:wakayama",
  "wakayama-city": "Wakayama:wakayama",
  "yakushi-ike-park": "Tokyo:machida",
  "yakushi-ji-temple": "Nara:nara",
  "yakushima-town": "Kagoshima:yakushima",
  "yamadera-yamagata": "Yamagata:yamagata",
  "yamagata-city": "Yamagata:yamagata",
  "yamanashi-fujiyoshida": "Yamanashi:fujiyoshida",
  "yamanashi-nishizawa-valley": "Yamanashi:kofu",
  "yamanashi-shosenkyo-gorge": "Yamanashi:kofu",
  "yamashita-park-yokohama": "Kanagawa:yokohama",
  yanaka: "Tokyo:taito",
  "yasaka-shrine": "Kyoto:kyoto",
  "yokohama-chinatown": "Kanagawa:yokohama",
  "yokohama-city": "Kanagawa:yokohama",
  "yokohama-cosmo-world": "Kanagawa:yokohama",
  "yokohama-landmark-tower-sky-garden": "Kanagawa:yokohama",
  "yokohama-marine-tower": "Kanagawa:yokohama",
  "yokohama-red-brick-warehouse": "Kanagawa:yokohama",
  "yokohama-zoorasia": "Kanagawa:yokohama",
  "yokosuka-city": "Kanagawa:yokosuka",
  "yonaha-maehama-beach-miyako": "Okinawa:miyakojima",
  "yonehara-beach-coral-ishigaki": "Okinawa:ishigaki",
  "yoyogi-park": "Tokyo:shibuya",
  "yufu-city": "Oita:yufu",
  "yugyo-ji": "Kanagawa:fujisawa",
  "yuigahama-beach": "Kanagawa:kamakura",
  "zao-fox-village-miyagi": "Miyagi:shiroishi",
  "zeniarai-benten": "Kanagawa:kamakura",
  "zoshigaya-kishimojindo": "Tokyo:toshima",
  zuihoden: "Miyagi:sendai",
};

const indexPath = path.join(
  process.cwd(),
  "src/shared/data/destinations-index.json",
);
const destinations = JSON.parse(
  fs.readFileSync(indexPath, "utf-8"),
) as Destination[];
const byId = new Map(
  destinations.map((destination) => [destination.id, destination]),
);

const failures: string[] = [];
const parentFor = new Map(Object.entries(PARENT_BY_DESTINATION_ID));
const gatewayFor = new Map(Object.entries(GATEWAY_BY_DESTINATION_ID));

// 1. Validate every map entry before mutating anything.
for (const [destinationId, parentId] of parentFor) {
  const destination = byId.get(destinationId);
  const parent = byId.get(parentId);
  if (!destination) {
    failures.push(
      `destination '${destinationId}' does not exist in the catalogue`,
    );
  } else if (!parent) {
    failures.push(
      `parent hub '${parentId}' (of '${destinationId}') does not exist`,
    );
  } else if (parent.role !== "hub") {
    failures.push(`parent '${parentId}' (of '${destinationId}') is not a hub`);
  } else if (parent.prefecture !== destination.prefecture) {
    failures.push(
      `parent '${parentId}' is in ${parent.prefecture} but '${destinationId}' is in ${destination.prefecture}`,
    );
  }
}

for (const [destinationId, hubId] of gatewayFor) {
  const destination = byId.get(destinationId);
  const hub = byId.get(hubId);
  if (!destination) {
    failures.push(`gateway destination '${destinationId}' does not exist`);
  } else if (!hub) {
    failures.push(
      `gateway hub '${hubId}' (of '${destinationId}') does not exist`,
    );
  } else if (hub.role !== "hub") {
    failures.push(
      `gateway hub '${hubId}' (of '${destinationId}') is not a hub`,
    );
  } else if (hub.prefecture !== destination.prefecture) {
    failures.push(
      `gateway hub '${hubId}' is in ${hub.prefecture} but '${destinationId}' is in ${destination.prefecture}`,
    );
  }
}

// 1b. Exhaustive, disjoint classification: every non-hub destination must be
//     classified exactly once as contained, gateway, or standalone/unparented.
const parentIds = new Set(parentFor.keys());
const gatewayIds = new Set(gatewayFor.keys());
const unparentedIds = new Set(UNPARENTED_DESTINATION_IDS);

for (const destination of destinations) {
  if (destination.role === "hub") continue;
  const inParent = parentIds.has(destination.id);
  const inGateway = gatewayIds.has(destination.id);
  const inUnparented = unparentedIds.has(destination.id);
  const classificationCount =
    Number(inParent) + Number(inGateway) + Number(inUnparented);

  if (classificationCount > 1) {
    failures.push(
      `destination '${destination.id}' is assigned to more than one classification set (parent=${inParent}, gateway=${inGateway}, unparented=${inUnparented})`,
    );
  } else if (
    classificationCount === 0 &&
    destination.relationships?.parentDestinationId
  ) {
    failures.push(
      `destination '${destination.id}' has parentDestinationId but is not in the containment map (stale mapping)`,
    );
  } else if (
    classificationCount === 0 &&
    destination.relationships?.gatewayHubId
  ) {
    failures.push(
      `destination '${destination.id}' has gatewayHubId but is not in the gateway map (stale mapping)`,
    );
  } else if (classificationCount === 0) {
    failures.push(
      `destination '${destination.id}' is not classified: it must be in exactly one of the containment map, the gateway map, or the unparented list`,
    );
  }
}

// 1c. Every map entry must be non-empty in the opposite set (parent and
//     gateway are mutually exclusive).
for (const destinationId of parentIds) {
  if (gatewayIds.has(destinationId)) {
    failures.push(
      `destination '${destinationId}' appears in both the containment and gateway maps`,
    );
  }
  if (unparentedIds.has(destinationId)) {
    failures.push(
      `destination '${destinationId}' appears in both the containment map and the unparented list`,
    );
  }
}
for (const destinationId of gatewayIds) {
  if (unparentedIds.has(destinationId)) {
    failures.push(
      `destination '${destinationId}' appears in both the gateway map and the unparented list`,
    );
  }
}

if (failures.length > 0) {
  console.error(`FAILED relationship validation (${failures.length}):`);
  for (const failure of failures) {
    console.error(`  - ${failure}`);
  }
  process.exit(1);
}

// 1d. Strip the legacy top-level hubId field. It duplicates
//     relationships.parentDestinationId, is not part of the Destination type,
//     and is not read by application code.
let strippedHubIds = 0;
for (const destination of destinations) {
  if ("hubId" in destination) {
    delete (destination as Record<string, unknown>).hubId;
    strippedHubIds++;
  }
}

// 2. Reconcile: apply only records that differ so untouched records keep their
//    exact serialization (minimal diff) while removed mappings propagate.
const managedIds = new Set([
  ...parentFor.keys(),
  ...gatewayFor.keys(),
  ...UNPARENTED_DESTINATION_IDS,
]);

let applied = 0;
for (const destination of destinations) {
  if (!managedIds.has(destination.id)) continue;
  const desiredParent = parentFor.get(destination.id);
  const desiredGateway = gatewayFor.get(destination.id);
  const current = destination.relationships ?? {};
  const currentParent = current.parentDestinationId;
  const currentGateway = current.gatewayHubId;

  if (currentParent === desiredParent && currentGateway === desiredGateway) {
    continue;
  }

  if (!destination.relationships) {
    destination.relationships = {};
  }
  if (desiredParent) {
    destination.relationships.parentDestinationId = desiredParent;
  } else {
    delete destination.relationships.parentDestinationId;
  }
  if (desiredGateway) {
    destination.relationships.gatewayHubId = desiredGateway;
  } else {
    delete destination.relationships.gatewayHubId;
  }
  if (Object.keys(destination.relationships).length === 0) {
    delete destination.relationships;
  }
  applied++;
}

// 3. Region overrides.
for (const [destinationId, region] of Object.entries(REGION_OVERRIDES)) {
  const destination = byId.get(destinationId);
  if (destination) {
    destination.region = region;
  }
}

// 4. Apply municipalityId from the independent map only. The map is the
//    single source of truth; it is never derived from a parent relationship.
//    Records no longer present in the map (e.g. moved to gateway/standalone)
//    have their municipalityId removed so a stale value cannot linger.
let municipalityAssigned = 0;
let municipalityRemoved = 0;
for (const destination of destinations) {
  const mapped = MUNICIPALITY_BY_DESTINATION_ID[destination.id];
  if (!mapped) {
    if (destination.municipalityId) {
      delete destination.municipalityId;
      municipalityRemoved++;
    }
    continue;
  }
  if (destination.municipalityId !== mapped) {
    destination.municipalityId = mapped;
    municipalityAssigned++;
  }
}

fs.writeFileSync(indexPath, `${JSON.stringify(destinations, null, 2)}\n`);
console.log(
  `Relationships reconciled: ${applied} of ${managedIds.size} managed destinations updated (${parentFor.size} containment, ${gatewayFor.size} gateway), ${strippedHubIds} legacy hubId fields stripped, ${municipalityAssigned} municipalityId assignments, ${municipalityRemoved} stale municipalityId fields removed.`,
);
