import {
  Compass,
  CalendarDays,
  MapPinned,
  CircleDot,
  Map,
  History,
  Trophy,
  Medal,
  BarChart3,
  UserRound,
  Settings2,
  HelpCircle,
  MessageSquareMore,
  ShieldCheck,
  Palette,
  Eye,
  Database,
  Zap,
  Rocket,
  Keyboard,
  Link as LinkIcon,
  Car,
  Sun,
  Moon,
  Laptop,
  Lock,
  CheckCircle2,
  Bookmark,
  Calendar,
  Search,
  LogOut,
  LogIn,
  Menu,
  X,
  ChevronDown,
  ArrowRight,
  CornerDownLeft,
} from "lucide-react";

export const Icons = {
  discover: Compass,
  plan: CalendarDays,
  passport: MapPinned,
  overview: CircleDot,
  japanMap: Map,
  timeline: History,
  achievements: Trophy,
  badges: Medal,
  statistics: BarChart3,
  profile: UserRound,
  settings: Settings2,
  help: HelpCircle,
  feedback: MessageSquareMore,
  security: ShieldCheck,
  appearance: Palette,
  accessibility: Eye,
  dataExport: Database,
  action: Zap,
  gettingStarted: Rocket,
  shortcuts: Keyboard,
  link: LinkIcon,
  car: Car,
  sun: Sun,
  moon: Moon,
  system: Laptop,
  lock: Lock,
  check: CheckCircle2,
  bookmark: Bookmark,
  calendar: Calendar,
  search: Search,
  logout: LogOut,
  login: LogIn,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  enter: CornerDownLeft,
};
